/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import model.CaixaEvento;
import model.ComboCaixa;
import model.ComboCaixaTableModel;
import model.ProdutoCaixa;
import model.ProdutoCaixaTableModel;
import model.dao.CaixaEventoDAO;
import model.dao.ComboCaixaDAO;
import model.dao.ProdutoCaixaDAO;
import utils.FormatUtils;

/**
 *
 */
public class CaixaView extends javax.swing.JDialog {

    CaixaEvento caixa;
    List<ProdutoCaixa> produtos;
    List<ComboCaixa> combos;
    ProdutoCaixaDAO produtoCaixaDAO = new ProdutoCaixaDAO();
    ComboCaixaDAO comboCaixaDAO = new ComboCaixaDAO();
    CaixaEventoDAO caixaEventoDAO = new CaixaEventoDAO();
    ProdutoCaixaTableModel tableModelProdutoCaixa;
    ComboCaixaTableModel tableModelComboCaixa;
    BigDecimal total;
    Integer totalUnidades;

    BigDecimal vendaDebito = BigDecimal.ZERO;
    BigDecimal vendaCredito = BigDecimal.ZERO;
    BigDecimal vendaDinheiro = BigDecimal.ZERO;
    BigDecimal vendaVale = BigDecimal.ZERO;

    public CaixaEvento getCaixa() {
        return caixa;
    }

    public void setCaixa(CaixaEvento caixa) {
        this.caixa = caixa;
    }

    /**
     * Creates new form BarView
     */
    public CaixaView(CaixaEvento caixa) {
        initComponents();
        this.caixa = caixa;
        labelCaixa.setText(caixa.getNome());

        textFieldCredito.setText(FormatUtils.formataDinheiroExibicao(caixa.getVendaCredito()));
        textFieldDebito.setText(FormatUtils.formataDinheiroExibicao(caixa.getVendaDebito()));
        textFieldDinheiro.setText(FormatUtils.formataDinheiroExibicao(caixa.getVendaDinheiro()));
        textFieldVale.setText(FormatUtils.formataDinheiroExibicao(caixa.getVendaVale()));

        try {
            produtos = produtoCaixaDAO.listarTodosPorCaixaEvento(caixa);
            tableModelProdutoCaixa = new ProdutoCaixaTableModel(produtos, this);
            tableProdutos.setModel(tableModelProdutoCaixa);

            combos = comboCaixaDAO.listarTodosPorCaixaEvento(caixa);
            tableModelComboCaixa = new ComboCaixaTableModel(combos);
            tableCombos.setModel(tableModelComboCaixa);

            textFieldNome.setVisible(false);
            jLabel1.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoEventoView.class.getName()).log(Level.SEVERE, null, ex);
        }

        total = BigDecimal.ZERO;
        totalUnidades = 0;

        for (ProdutoCaixa p : produtos) {
            total = total.add(p.getProduto().getValorVenda().multiply(new BigDecimal(p.getQuantidade())));
            totalUnidades = totalUnidades + p.getQuantidade();
        }

        for (ComboCaixa c : combos) {
            total = total.add(c.getProduto().getValorVenda().multiply(new BigDecimal(c.getQuantidade())));
            totalUnidades = totalUnidades + c.getQuantidade();
        }

        labelTotalVendas.setText(FormatUtils.formataDinheiroExibicao(total));
        labelUnidades.setText(String.valueOf(totalUnidades));

        tableProdutos.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                recalcularValores();
            }
        });
        
        tableCombos.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                recalcularValores();
            }
        });

        recalculaTotais();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelCaixa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldDebito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldCredito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldDinheiro = new javax.swing.JTextField();
        textFieldVale = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelDiferenca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTotalVendas = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        labelUnidades = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCombos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas por Caixa");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome");

        labelCaixa.setText("Caixa 001");

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Valor de Venda", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        jLabel2.setText("Vendas Produtos");

        jLabel3.setText("Débito");

        textFieldDebito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDebitoFocusLost(evt);
            }
        });

        jLabel4.setText("Crédito");

        textFieldCredito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldCreditoFocusLost(evt);
            }
        });

        jLabel5.setText("Dinheiro");

        textFieldDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDinheiroFocusLost(evt);
            }
        });

        textFieldVale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldValeFocusLost(evt);
            }
        });

        jLabel6.setText("Vale");

        jLabel7.setText("Total");

        labelTotal.setText("1000");

        jLabel8.setText("Diferença");

        labelDiferenca.setText("50");

        jLabel9.setText("Total de Vendas:");

        labelTotalVendas.setText("200.000");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        labelUnidades.setText("10");

        jLabel10.setText("unidades");

        jLabel11.setText("Vendas Combos");

        tableCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCombos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(labelCaixa))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTotalVendas)
                                .addGap(18, 18, 18)
                                .addComponent(labelUnidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldNome)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(labelTotal))
                                        .addGap(77, 77, 77)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(labelDiferenca)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(textFieldDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(textFieldCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(textFieldVale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textFieldCredito, textFieldDebito, textFieldDinheiro, textFieldVale});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelTotalVendas)
                    .addComponent(labelUnidades)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(textFieldDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(textFieldCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(textFieldDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(textFieldVale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(labelDiferenca))
                .addGap(23, 23, 23)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        caixa.setTotalVendido(totalUnidades);
        caixa.setValorTotalVendido(total);

        caixa.setVendaDebito(vendaDebito);
        caixa.setVendaCredito(vendaCredito);
        caixa.setVendaDinheiro(vendaDinheiro);
        caixa.setVendaVale(vendaVale);

        try {
            caixaEventoDAO.editar(caixa);
            JOptionPane.showMessageDialog(this, "Dados cadastrados com sucesso!", "Caixa Cadastrado", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(CaixaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        FechamentoView fechamentoView = new FechamentoView(caixa.getEvento());
        fechamentoView.setLocationRelativeTo(this);
        fechamentoView.setAlwaysOnTop(true);
        fechamentoView.setModal(true);
        fechamentoView.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void textFieldDebitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDebitoFocusLost
        recalculaTotais();
    }//GEN-LAST:event_textFieldDebitoFocusLost

    private void textFieldCreditoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCreditoFocusLost
        recalculaTotais();
    }//GEN-LAST:event_textFieldCreditoFocusLost

    private void textFieldDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDinheiroFocusLost
        recalculaTotais();
    }//GEN-LAST:event_textFieldDinheiroFocusLost

    private void textFieldValeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldValeFocusLost
        recalculaTotais();
    }//GEN-LAST:event_textFieldValeFocusLost

    private void recalculaTotais() {
        vendaDebito = BigDecimal.ZERO;
        vendaCredito = BigDecimal.ZERO;
        vendaDinheiro = BigDecimal.ZERO;
        vendaVale = BigDecimal.ZERO;

        if (!textFieldDebito.getText().trim().isEmpty()) {
            vendaDebito = new BigDecimal(FormatUtils.ajustaFormato(textFieldDebito.getText().trim()));
        }

        if (!textFieldCredito.getText().trim().isEmpty()) {
            vendaCredito = new BigDecimal(FormatUtils.ajustaFormato(textFieldCredito.getText().trim()));
        }

        if (!textFieldDinheiro.getText().trim().isEmpty()) {
            vendaDinheiro = new BigDecimal(FormatUtils.ajustaFormato(textFieldDinheiro.getText().trim()));
        }

        if (!textFieldVale.getText().trim().isEmpty()) {
            vendaVale = new BigDecimal(FormatUtils.ajustaFormato(textFieldVale.getText().trim()));
        }

        BigDecimal totalVendido = BigDecimal.ZERO;
        totalVendido = totalVendido.add(vendaDebito).add(vendaCredito).add(vendaDinheiro).add(vendaVale);

        labelTotal.setText(FormatUtils.formataDinheiroExibicao(totalVendido));
        labelDiferenca.setText(FormatUtils.formataDinheiroExibicao(totalVendido.subtract(total)));
    }

    private void recalcularValores() {
        total = BigDecimal.ZERO;
        totalUnidades = 0;

        for (ProdutoCaixa p : produtos) {
            total = total.add(p.getProduto().getValorVenda().multiply(new BigDecimal(p.getQuantidade())));
            totalUnidades = totalUnidades + p.getQuantidade();
        }

        for (ComboCaixa c : combos) {
            total = total.add(c.getProduto().getValorVenda().multiply(new BigDecimal(c.getQuantidade())));
            totalUnidades = totalUnidades + c.getQuantidade();
        }

        labelTotalVendas.setText(FormatUtils.formataDinheiroExibicao(total));
        labelUnidades.setText(String.valueOf(totalUnidades));

        recalculaTotais();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCaixa;
    private javax.swing.JLabel labelDiferenca;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalVendas;
    private javax.swing.JLabel labelUnidades;
    private javax.swing.JTable tableCombos;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField textFieldCredito;
    private javax.swing.JTextField textFieldDebito;
    private javax.swing.JTextField textFieldDinheiro;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldVale;
    // End of variables declaration//GEN-END:variables

}
